/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import { Contract, ContractTransaction } from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DepositLibInterface extends ethers.utils.Interface {
  functions: {};

  events: {
    "DepositLock(address,address,uint256)": EventFragment;
    "DepositUnlock(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DepositLock"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DepositUnlock"): EventFragment;
}

export class DepositLib extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DepositLibInterface;

  functions: {};

  callStatic: {};

  filters: {
    DepositLock(
      token: string | null,
      from: string | null,
      amount: null
    ): EventFilter;

    DepositUnlock(
      token: string | null,
      to: string | null,
      amount: null
    ): EventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
