/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DepositLibInterface extends ethers.utils.Interface {
  functions: {
    "c_0xca43b61b(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "c_0xca43b61b",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "c_0xca43b61b",
    data: BytesLike
  ): Result;

  events: {};
}

export class DepositLib extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DepositLibInterface;

  functions: {
    c_0xca43b61b(
      c__0xca43b61b: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "c_0xca43b61b(bytes32)"(
      c__0xca43b61b: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  c_0xca43b61b(
    c__0xca43b61b: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  "c_0xca43b61b(bytes32)"(
    c__0xca43b61b: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    c_0xca43b61b(
      c__0xca43b61b: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "c_0xca43b61b(bytes32)"(
      c__0xca43b61b: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    c_0xca43b61b(
      c__0xca43b61b: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "c_0xca43b61b(bytes32)"(
      c__0xca43b61b: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    c_0xca43b61b(
      c__0xca43b61b: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "c_0xca43b61b(bytes32)"(
      c__0xca43b61b: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
