/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IExecutableInterface extends ethers.utils.Interface {
  functions: {
    "canExecute(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "canExecute", values: [string]): string;

  decodeFunctionResult(functionFragment: "canExecute", data: BytesLike): Result;

  events: {};
}

export class IExecutable extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IExecutableInterface;

  functions: {
    canExecute(
      executer: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "canExecute(address)"(
      executer: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  canExecute(
    executer: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "canExecute(address)"(
    executer: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    canExecute(executer: string, overrides?: CallOverrides): Promise<boolean>;

    "canExecute(address)"(
      executer: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    canExecute(executer: string, overrides?: Overrides): Promise<BigNumber>;

    "canExecute(address)"(
      executer: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    canExecute(
      executer: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "canExecute(address)"(
      executer: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
