/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface OwnableCelesteInterface extends ethers.utils.Interface {
  functions: {
    "setOwner(address)": FunctionFragment;
    "decideDispute(uint256,uint8)": FunctionFragment;
    "disputes(uint256)": FunctionFragment;
    "feeToken()": FunctionFragment;
    "feeAmount()": FunctionFragment;
    "getDisputeFees()": FunctionFragment;
    "submitEvidence(uint256,address,bytes)": FunctionFragment;
    "closeEvidencePeriod(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "computeRuling(uint256)": FunctionFragment;
    "createDispute(uint256,bytes)": FunctionFragment;
    "rule(uint256)": FunctionFragment;
    "getDisputeManager()": FunctionFragment;
    "currentId()": FunctionFragment;
    "setFee(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "setOwner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "decideDispute",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "feeToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "feeAmount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDisputeFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitEvidence",
    values: [BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closeEvidencePeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "computeRuling",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createDispute",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "rule", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getDisputeManager",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "currentId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decideDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disputes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeAmount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDisputeFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeEvidencePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "computeRuling",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rule", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDisputeManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "currentId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;

  events: {};
}

export class OwnableCeleste extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: OwnableCelesteInterface;

  functions: {
    setOwner(
      _owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setOwner(address)"(
      _owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    decideDispute(
      _disputeId: BigNumberish,
      _state: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "decideDispute(uint256,uint8)"(
      _disputeId: BigNumberish,
      _state: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    disputes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, number] & { subject: string; state: number }>;

    "disputes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, number] & { subject: string; state: number }>;

    feeToken(overrides?: CallOverrides): Promise<[string]>;

    "feeToken()"(overrides?: CallOverrides): Promise<[string]>;

    feeAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    "feeAmount()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getDisputeFees(
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber]>;

    "getDisputeFees()"(
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber]>;

    submitEvidence(
      _disputeId: BigNumberish,
      _submitter: string,
      _evidence: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "submitEvidence(uint256,address,bytes)"(
      _disputeId: BigNumberish,
      _submitter: string,
      _evidence: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    closeEvidencePeriod(
      _disputeId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "closeEvidencePeriod(uint256)"(
      _disputeId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    computeRuling(
      _disputeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, number] & { subject: string; finalRuling: number }>;

    "computeRuling(uint256)"(
      _disputeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, number] & { subject: string; finalRuling: number }>;

    createDispute(
      _possibleRulings: BigNumberish,
      _metadata: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createDispute(uint256,bytes)"(
      _possibleRulings: BigNumberish,
      _metadata: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    rule(
      _disputeId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "rule(uint256)"(
      _disputeId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getDisputeManager(overrides?: CallOverrides): Promise<[string]>;

    "getDisputeManager()"(overrides?: CallOverrides): Promise<[string]>;

    currentId(overrides?: CallOverrides): Promise<[BigNumber]>;

    "currentId()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    setFee(
      _feeToken: string,
      _feeAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setFee(address,uint256)"(
      _feeToken: string,
      _feeAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  setOwner(_owner: string, overrides?: Overrides): Promise<ContractTransaction>;

  "setOwner(address)"(
    _owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  decideDispute(
    _disputeId: BigNumberish,
    _state: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "decideDispute(uint256,uint8)"(
    _disputeId: BigNumberish,
    _state: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  disputes(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, number] & { subject: string; state: number }>;

  "disputes(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, number] & { subject: string; state: number }>;

  feeToken(overrides?: CallOverrides): Promise<string>;

  "feeToken()"(overrides?: CallOverrides): Promise<string>;

  feeAmount(overrides?: CallOverrides): Promise<BigNumber>;

  "feeAmount()"(overrides?: CallOverrides): Promise<BigNumber>;

  getDisputeFees(
    overrides?: CallOverrides
  ): Promise<[string, string, BigNumber]>;

  "getDisputeFees()"(
    overrides?: CallOverrides
  ): Promise<[string, string, BigNumber]>;

  submitEvidence(
    _disputeId: BigNumberish,
    _submitter: string,
    _evidence: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "submitEvidence(uint256,address,bytes)"(
    _disputeId: BigNumberish,
    _submitter: string,
    _evidence: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  closeEvidencePeriod(
    _disputeId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "closeEvidencePeriod(uint256)"(
    _disputeId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  computeRuling(
    _disputeId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, number] & { subject: string; finalRuling: number }>;

  "computeRuling(uint256)"(
    _disputeId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, number] & { subject: string; finalRuling: number }>;

  createDispute(
    _possibleRulings: BigNumberish,
    _metadata: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createDispute(uint256,bytes)"(
    _possibleRulings: BigNumberish,
    _metadata: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  rule(
    _disputeId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "rule(uint256)"(
    _disputeId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getDisputeManager(overrides?: CallOverrides): Promise<string>;

  "getDisputeManager()"(overrides?: CallOverrides): Promise<string>;

  currentId(overrides?: CallOverrides): Promise<BigNumber>;

  "currentId()"(overrides?: CallOverrides): Promise<BigNumber>;

  setFee(
    _feeToken: string,
    _feeAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setFee(address,uint256)"(
    _feeToken: string,
    _feeAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    setOwner(_owner: string, overrides?: CallOverrides): Promise<void>;

    "setOwner(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    decideDispute(
      _disputeId: BigNumberish,
      _state: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "decideDispute(uint256,uint8)"(
      _disputeId: BigNumberish,
      _state: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    disputes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, number] & { subject: string; state: number }>;

    "disputes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, number] & { subject: string; state: number }>;

    feeToken(overrides?: CallOverrides): Promise<string>;

    "feeToken()"(overrides?: CallOverrides): Promise<string>;

    feeAmount(overrides?: CallOverrides): Promise<BigNumber>;

    "feeAmount()"(overrides?: CallOverrides): Promise<BigNumber>;

    getDisputeFees(
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber]>;

    "getDisputeFees()"(
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber]>;

    submitEvidence(
      _disputeId: BigNumberish,
      _submitter: string,
      _evidence: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "submitEvidence(uint256,address,bytes)"(
      _disputeId: BigNumberish,
      _submitter: string,
      _evidence: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    closeEvidencePeriod(
      _disputeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "closeEvidencePeriod(uint256)"(
      _disputeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    computeRuling(
      _disputeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, number] & { subject: string; finalRuling: number }>;

    "computeRuling(uint256)"(
      _disputeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, number] & { subject: string; finalRuling: number }>;

    createDispute(
      _possibleRulings: BigNumberish,
      _metadata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "createDispute(uint256,bytes)"(
      _possibleRulings: BigNumberish,
      _metadata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rule(
      _disputeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { subject: string; ruling: BigNumber }>;

    "rule(uint256)"(
      _disputeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { subject: string; ruling: BigNumber }>;

    getDisputeManager(overrides?: CallOverrides): Promise<string>;

    "getDisputeManager()"(overrides?: CallOverrides): Promise<string>;

    currentId(overrides?: CallOverrides): Promise<BigNumber>;

    "currentId()"(overrides?: CallOverrides): Promise<BigNumber>;

    setFee(
      _feeToken: string,
      _feeAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setFee(address,uint256)"(
      _feeToken: string,
      _feeAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    setOwner(_owner: string, overrides?: Overrides): Promise<BigNumber>;

    "setOwner(address)"(
      _owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    decideDispute(
      _disputeId: BigNumberish,
      _state: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "decideDispute(uint256,uint8)"(
      _disputeId: BigNumberish,
      _state: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    disputes(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "disputes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    feeToken(overrides?: CallOverrides): Promise<BigNumber>;

    "feeToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    feeAmount(overrides?: CallOverrides): Promise<BigNumber>;

    "feeAmount()"(overrides?: CallOverrides): Promise<BigNumber>;

    getDisputeFees(overrides?: CallOverrides): Promise<BigNumber>;

    "getDisputeFees()"(overrides?: CallOverrides): Promise<BigNumber>;

    submitEvidence(
      _disputeId: BigNumberish,
      _submitter: string,
      _evidence: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "submitEvidence(uint256,address,bytes)"(
      _disputeId: BigNumberish,
      _submitter: string,
      _evidence: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    closeEvidencePeriod(
      _disputeId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "closeEvidencePeriod(uint256)"(
      _disputeId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    computeRuling(
      _disputeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "computeRuling(uint256)"(
      _disputeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createDispute(
      _possibleRulings: BigNumberish,
      _metadata: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createDispute(uint256,bytes)"(
      _possibleRulings: BigNumberish,
      _metadata: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    rule(_disputeId: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "rule(uint256)"(
      _disputeId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getDisputeManager(overrides?: CallOverrides): Promise<BigNumber>;

    "getDisputeManager()"(overrides?: CallOverrides): Promise<BigNumber>;

    currentId(overrides?: CallOverrides): Promise<BigNumber>;

    "currentId()"(overrides?: CallOverrides): Promise<BigNumber>;

    setFee(
      _feeToken: string,
      _feeAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setFee(address,uint256)"(
      _feeToken: string,
      _feeAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    setOwner(
      _owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setOwner(address)"(
      _owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    decideDispute(
      _disputeId: BigNumberish,
      _state: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "decideDispute(uint256,uint8)"(
      _disputeId: BigNumberish,
      _state: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    disputes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "disputes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    feeToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "feeToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "feeAmount()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDisputeFees(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getDisputeFees()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    submitEvidence(
      _disputeId: BigNumberish,
      _submitter: string,
      _evidence: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "submitEvidence(uint256,address,bytes)"(
      _disputeId: BigNumberish,
      _submitter: string,
      _evidence: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    closeEvidencePeriod(
      _disputeId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "closeEvidencePeriod(uint256)"(
      _disputeId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    computeRuling(
      _disputeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "computeRuling(uint256)"(
      _disputeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createDispute(
      _possibleRulings: BigNumberish,
      _metadata: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createDispute(uint256,bytes)"(
      _possibleRulings: BigNumberish,
      _metadata: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    rule(
      _disputeId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "rule(uint256)"(
      _disputeId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getDisputeManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getDisputeManager()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    currentId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "currentId()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setFee(
      _feeToken: string,
      _feeAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setFee(address,uint256)"(
      _feeToken: string,
      _feeAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
