/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { DepositLib } from "../DepositLib";

export class DepositLib__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<DepositLib> {
    return super.deploy(overrides || {}) as Promise<DepositLib>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DepositLib {
    return super.attach(address) as DepositLib;
  }
  connect(signer: Signer): DepositLib__factory {
    return super.connect(signer) as DepositLib__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DepositLib {
    return new Contract(address, _abi, signerOrProvider) as DepositLib;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0xca43b61b",
        type: "bytes32",
      },
    ],
    name: "c_0xca43b61b",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x60e0610052600b82828239805160001a607314610045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80631fa90114146038575b600080fd5b604e6004803603810190604a91906066565b6050565b005b50565b6000813590506060816096565b92915050565b600060208284031215607757600080fd5b60006083848285016053565b91505092915050565b6000819050919050565b609d81608c565b811460a757600080fd5b5056fea2646970667358221220b91a7fff344000d32736feaaa9b7a4aa9b469d72dbbc16e049e9890480794a3664736f6c63430008010033";
