/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IArbitrator } from "../IArbitrator";

export class IArbitrator__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IArbitrator {
    return new Contract(address, _abi, signerOrProvider) as IArbitrator;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "getDisputeFees",
    outputs: [
      {
        name: "recipient",
        type: "address",
      },
      {
        name: "feeToken",
        type: "address",
      },
      {
        name: "feeAmount",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_disputeId",
        type: "uint256",
      },
      {
        name: "_submitter",
        type: "address",
      },
      {
        name: "_evidence",
        type: "bytes",
      },
    ],
    name: "submitEvidence",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_possibleRulings",
        type: "uint256",
      },
      {
        name: "_metadata",
        type: "bytes",
      },
    ],
    name: "createDispute",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_subject",
        type: "address",
      },
      {
        name: "_disputeId",
        type: "uint256",
      },
    ],
    name: "closeEvidencePeriod",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_disputeId",
        type: "uint256",
      },
    ],
    name: "rule",
    outputs: [
      {
        name: "subject",
        type: "address",
      },
      {
        name: "ruling",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];
