/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IExecutable } from "../IExecutable";

export class IExecutable__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IExecutable {
    return new Contract(address, _abi, signerOrProvider) as IExecutable;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "executer",
        type: "address",
      },
    ],
    name: "canExecute",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
