// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  Address,
  DataSourceTemplate,
  DataSourceContext
} from "@graphprotocol/graph-ts";

export class DisputeManager extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("DisputeManager", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "DisputeManager",
      [address.toHex()],
      context
    );
  }
}

export class JurorsRegistry extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("JurorsRegistry", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "JurorsRegistry",
      [address.toHex()],
      context
    );
  }
}

export class Voting extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("Voting", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext("Voting", [address.toHex()], context);
  }
}

export class Treasury extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("Treasury", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "Treasury",
      [address.toHex()],
      context
    );
  }
}

export class Subscriptions extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("Subscriptions", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "Subscriptions",
      [address.toHex()],
      context
    );
  }
}

export class BrightIdRegister extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("BrightIdRegister", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "BrightIdRegister",
      [address.toHex()],
      context
    );
  }
}
