name: "E2E"
description: "Automated end-to-end testing"
runs:
  - uses: UnlyEd/github-action-await-vercel@v1.2.14
    id: wait-vercel
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    with:
      deployment-url: quests-55n3stz76-1hive.vercel.app
      timeout: 10 # Wait for 10 seconds before failing
  - name: Run E2E test
    run: yarn e2e
