on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
jobs:
  e2e:
    name: E2E
    description: "Automated end-to-end testing"
    runs-on: ubuntu-latest
    steps:
      - uses: UnlyEd/github-action-await-vercel@v1.2.14
        id: wait-vercel
        env:
          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
        with:
          deployment-url: quests-git-end-to-end-automated-tests-1hive.vercel.app
          timeout: 900 # Wait for 15 minutes before failing
      - name: Run E2E test
        run: yarn e2e
