name: Deploy & E2E
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to Vercel Action
      uses: BetaHuhn/deploy-to-vercel-action@v1
      with:
        VERCEL_SCOPE: '1hive'
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
  e2e:
    runs-on: ubuntu-latest
    - name: Checkout
      uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: yarn ci
        shell: bash
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Run E2E test
        env:
          E2E_SECRET_WORDS: ${{secrets.E2E_SECRET_WORDS}}
        run: xvfb-run --auto-servernum yarn e2e
