name: E2E
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: yarn ci
        shell: bash
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Wait for deploy to finish
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: "deploy"
          repo-token: ${{ secrets.GH_PAT }}
          wait-interval: 10
          allowed-conclusions: success,cancelled
      - name: Run E2E test
        env:
          E2E_SECRET_WORDS: ${{secrets.E2E_SECRET_WORDS}}
        run: xvfb-run --auto-servernum yarn e2e
